Master
andferrari/PAINTER.jl pull request #28
Opened 2016-10-24 14:04 UTC by DeVerMyst

Ready for release
Contains 3 demo: old one, gravity bc16 and giant monochromatic bc04.
Possibility to initialise PAINTER automatically with keyword ``init =
true`` : alpha, beta rhow_y_xi and rho_y_gamma are automaticaly setted.

Data are normalized by global flux which allow to Use in most part of
the case ready parameters.

Doc is updated

2016-10-24 15:13 UTC, andferrari reviewed
bug to correct

2016-10-24 15:13 UTC, andferrari commented on src/paintertools.jl
> +    if init == "autoinit"
@DeVerMyst should be  `if autoinit == "auto"`

2016-10-24 15:28 UTC, DeVerMyst commented on src/paintertools.jl
> +    if init == "autoinit"
Yes totally ! 
last minute modification :)

2016-10-24 18:05 UTC, andferrari requested changes

2016-10-24 18:05 UTC, andferrari commented on src/paintertools.jl
> +    if init == "autoinit"
c'est à toi de faire la modif, moi je ne peux pas !

2016-10-25 06:56 UTC, merged

2016-10-25 18:22 UTC, DeVerMyst commented
Ah ok, je pensais que tu avais la main dessus.
C'est fait !

2016-10-24 20:05 GMT+02:00 André Ferrari <notifications@github.com>:

> *@andferrari* requested changes on this pull request.
> ------------------------------
>
> In src/paintertools.jl
> <https://github.com/andferrari/PAINTER.jl/pull/28#pullrequestreview-5504940>
> :
>
> >    # Initialise Data and xinit from V2 and flux
> -    PDATA,OIDATA = painterautoparametersinit(PDATA,OIDATA,flux)
> +    if init == "autoinit"
>
> c'est à toi de faire la modif, moi je ne peux pas !
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andferrari/PAINTER.jl/pull/28#pullrequestreview-5504940>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKOiGZGJbV9s3CAwgTF6rPLU4DhJ7zN3ks5q3PNngaJpZM4Ke1C0>
> .
>